version: "3.8"
services:
  mapillary_tools:
    build: https://github.com/mapillary/mapillary_tools.git#:docker
    command: >-
      mapillary_tools video_process_and_upload $INPUT
        --user_name $MAPILLARY_USER
        --geotag_source "blackvue_videos"
        --geotag_source_path $INPUT
        --interpolate_directions
        --video_sample_interval 0.5
        --device_make "Blackvue"
        --device_model "DR900S-1CH"
        --overwrite_EXIF_gps_tag
        --duplicate_distance 1.0
        --skip_process_errors
    volumes:
      - ./config.mapillary:/root/.config/mapillary
      - ./to_upload:/to_upload
    environment:
      PYTHONUNBUFFERED: 1

